version: '3.8'

services:
  postgres:
    image: postgres:18-alpine
    container_name: facility-kanban-postgres
    environment:
      POSTGRES_DB: facility_kanban
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - facility-kanban-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend-spring
      dockerfile: Dockerfile
    container_name: facility-kanban-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/facility_kanban
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - facility-kanban-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  facility-kanban-network:
    driver: bridge
